# All landing page object locators will be present here
button_dropdown_id = "id:dLabel"
dashboard_id = "id:j_projLPCaption"
button_new_id = "id:newRequestNewButton"
link_browse_xpath = "xpath://a[contains(text(),'Browse')]"
input_search_xpath = "xpath://*[@id='submit_projects_project_tree_container']/div/div[2]/input"
link_btv_project_id = "id:node-SBM_PROJECT-project_471-link"
text_submit_into_id = "id:issuedetailsLabel"
select_look_in_id = "id:j_lookInSelect"
spinner = "xpath://*[@id='ajaxloader']/div/img"
